version: 2
jobs: 
  build-assets:
    docker: 
      - image: bitnami/node:11.15.0
    steps:
      - checkout
      - run:
          name: Get JS Deps
          command: yarn install
      - run: 
          name: Build app 
          command: yarn build

workflows:
  version: 2 
  build:
    jobs:
      - build-assets
