name: Ship
on:
  push:
    branches:
      - master


jobs:
  upload-to-docker:
    name: Deploy to Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node Version
        uses: actions/setup-node@master
        with:
          version: 12.0.0

      - name: Get deps
        run: npm build

      - name: Build Docker Image
        run: make build

      - name: Log into Docker
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push to Docker
        run: make push

      - name: Publish Slack Notification
        uses: rtCamp/action-slack-notify@master


